imports:
  - resource: config.yml

parameters:
  order_provider.url_prefix: /app_dev.php

framework:
  profiler:
    enabled: true

web_profiler:
  toolbar: true
  intercept_redirects: false

swiftmailer:
  disable_delivery: true

monolog:
  handlers:
    main:
      type: stream
      path: '%kernel.logs_dir%/%kernel.environment%.log'
      level: debug
      channels: ['!event']
    console:
      type: console
      channels: ['!event', '!doctrine']
