imports:
  - resource: parameters.yml

framework:
  secret: '%secret%'
  session:
    handler_id: session.handler.native_file
    save_path: '%kernel.root_dir%/sessions/%kernel.environment%'
  templating:
    engines: ['twig']
  http_method_override: true

twig:
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'

markdown_web:
  directory: '%kernel.root_dir%/../web/'
  site:
    title: Celostní fyzioterapie
    author: Bc. Markéta Schillerová
