app:
    resource: '@AppBundle/Controller/'
    type: annotation

order:
    resource: '@OrderBundle/Controller/'
    type: annotation
    prefix: /order

markdown_web:
    resource: '@MarkdownWebBundle/Controller/'
    type: annotation
