services:
  markdown_web.config: # TODO move to MarkdownWebExtension
    class: PetrKnap\Symfony\MarkdownWeb\DependencyInjection\MarkdownWebConfiguration
  markdown_web.twig: # TODO move to MarkdownWebExtension
    class: PetrKnap\Symfony\MarkdownWeb\MarkdownWebTwigExtension
    autowire: true
    tags:
      - name: twig.extension
  markdown_web.crawler: # TODO move to MarkdownWebExtension
    class: PetrKnap\Symfony\MarkdownWeb\Service\Crawler
